version: '3.2'

networks:
  integration-test:

services:
  test:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    environment:
      - AUTHORIZATION_KEY="November 10, 2009"
      - PORT=":2565"
      - DATABASE_URL="postgres://root:root@postgres:5432/expenses-test-db?sslmode=disable"
    volumes:
      - .:/go/src/target
    depends_on:
      - postgres
    networks:
      - integration-test


  postgres:
  image: postgres:12.12
  environment:
    POSTGRES_USER: root
    POSTGRES_PASSWORD: root
    POSTGRES_DB: expenses-test-db
  ports:
    - 5432:5432
  restart: on-failure
  volumes:
    - ./postgres:/var/lib/postgresql/data
  networks:
    - integration-test

  
  